server:
  host: "localhost"
  port: 8080
  cors:
    allowed_origins:
      - "http://localhost:3000"
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Content-Type"
      - "Authorization"

jwt:
  secret_key: "your_secret_key"
  expiry_hours: 24

storage:
  event_file: "data/event.json"
  hall_file: "data/hall.json"
  user_file: "data/user.json" 